### ISSUE TITLE
Меню должно вести себя одинаково везде

### ISSUE THREAD

**Issue by Eneyer** [SonicGD/biowareru#30]
Статьи >> www.bioware.ru >> BRC интервью - Эта цепочка закачивается одним пунктом в меню, и чтобы на него перейти нужно кликнуть на "BRC интервью".
Файлы >> Dragon Age III >> Книги - Эта цепочка тоже заканчивается одним пунктом, но в "книги" перебрасывает сразу после нажатия "Dragon Age III", хотя там ожидаешь увидеть еще один список.

**Comment by SonicGD** [comment]
Да, это косяк старой менюшки, в новой ок будет.
