### ISSUE TITLE
Правки форума

### ISSUE THREAD

**Issue by SonicGD** [SonicGD/biowareru#40]
- [x] Вокруг изображений белые рамки
- [x] ~~Дублируются прикрепленные изображения~~
- [x] Не работают тег таблиц
- [x]  ~~Не работают цитаты в мобильной версии~~
- [x]  Не всюду раскрашено (https://forum.bioware.ru/topic/31390/?do=findComment&comment=2973898 , https://forum.bioware.ru/profile/1/?tab=field_core_pfield_12 , https://forum.bioware.ru/modcp/reports/5056/ , https://forum.bioware.ru/settings/ (все пункты дальше в меню)
- [x]  Ресайз аватарки не работает в форме ответа или в миниатюре сверху сайта
- [x]  ~~Вернуть кнопку Источник. Ее видят только админы\модеры~~
- [x]  Изначальный размер смайлов сделать меньше
- [x] ~~После перехода в режим предпросмотра сообщения нельзя вернуться обратно~~
- [x]  Большие отступы, при разделении текста на абзацы
- [x] ~~Список страниц сверху перенести под шапку.~~
- [x] Нельзя переголосовать в опросах
- [x]  ~~Кнопка "сохранить" после редактирования поста работает строго на большом экране. На мобильном устройстве или даже если на мониторе свернуть браузер в половину экрана, уже ничего не сохраняет, а просто зависает и все.~~
- [x] Вернуть отображение подписи в ЛС
- [x] И вернуть бы ещё возможность редактировать текст подписи пользователя, как в посте. А то там теперь сильно урезаны функции обработки текста, даже сдвигать в сторону его тоже нельзя.
- [x] https://forum.bioware.ru/topic/31390/?do=findComment&comment=2970675
- [x] Спойлер не отделяется от основного сообщения, особенно если спойлеры подряд
- [x] ~~И у меня, похоже, какой-то индивидуальный баг) изменять сообщения могу только с большого компа. С мобилки нигде не позволяет, ни в темах, ни в личке. Кнопка сохранить как бы подвисает, и все. Огорчительно.~~
- [x] ~~Вообщем не работают у меня оповещения. При комментирование моего статуса или цитировании - все нормально, оповещает, а если кто-то пишет в тему на которую я подписан - тишина. Уже все перепробовал. И на сколько я понял, я такой не один.~~
- [x] ~~Вчера ставила себе белое оформление, сегодня захожу - опять чёрное. Пришлось менять на дефолт.~~
- [x] Категории и разделы в названии форума https://forum.bioware.ru
- [x] Уменьшить дефолтный размер вставляемого ютюб-видео
- [x] При смене тайтла новости он не меняется на форуме
- [x] У многих там-сям возникает баг с невозможностью отправки сообщений
- [ ] Не все могут править шапки своих тем
- [ ] Супермодеры не видят жалобы
- [ ] Ачивки
- [ ] Бан от тем
- [ ] Невозможность удалять и добавлять новый опрос в тему
- [ ] https://forum.bioware.ru/topic/292/?do=findComment&comment=2981689
- [ ] https://forum.bioware.ru/topic/292/?do=findComment&comment=2981988
- [ ] при удалении новости, она не удаляется с форума
- [ ] не обновляется название новости на форуме

**Comment by SonicGD** [comment]
> Вернуть кнопку Источник. Ее видят только админы\модеры

Что это такое вообще?)

**Comment by SonicGD** [comment]
> Вокруг изображений белые рамки

Ссылку

**Comment by SonicGD** [comment]
> Дублируются прикрепленные изображения

Ссылку

**Comment by SonicGD** [comment]
@Dragnio давай, подключайся)

**Comment by Dragnio** [comment]
> Что это такое вообще?)

где можно вручную код хтмл исправлять

> Ссылку

https://forum.bioware.ru/topic/27538/ (рамка)
https://forum.bioware.ru/topic/26491/?do=findComment&comment=2689083 (дубль)

**Comment by SonicGD** [comment]
Понял

**Comment by SonicGD** [comment]
@Dragnio а в новых сообщениях тоже дублируются прикрепленные изображения? Для старых это скорее всего бага конвертатора и мы это не поправим.

**Comment by SonicGD** [comment]
> где можно вручную код хтмл исправлять

Ты предлагаешь её всем вернуть прям? Насколько это оправданно?

**Comment by SonicGD** [comment]
> Изначальный размер смайлов сделать меньше

Мб стоит просто какой-то другой набор смайлов найти.

**Comment by SonicGD** [comment]
> После перехода в режим предпросмотра сообщения нельзя вернуться обратно

Вот же оно:
![image](https://cloud.githubusercontent.com/assets/1222013/16840381/d382402c-49ed-11e6-8f42-a64a09fe1b6b.png)

**Comment by SonicGD** [comment]
> Список страниц сверху перенести под шапку.

Учитывая как выводится первый пост - пока что нереально.

**Comment by Dragnio** [comment]
> Ты предлагаешь её всем вернуть прям? Насколько это оправданно?

не уверен, что теперь сильно. Пусть админомодеры тогда только
