### ISSUE TITLE
Сделать поиск по сайту

### ISSUE THREAD

**Issue by Eneyer** [SonicGD/biowareru#8]

**Comment by SonicGD** [comment]
Предлагаю сделать страницу поиска в следующем варианте.

Ищем во всех имеющихся разделах, потом показываем результаты блоками
- Игры
- Новости
- Статьи
- Файлы
- Картинки

В каждом блоке выводим несколько результатов, а под ними ссылку на все страницу поиска по блоку, где выводим уже все результаты этого блока.
